# Generated by Django 4.1.7 on 2023-04-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_article_likes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='null', upload_to='products', verbose_name='Imagen'),
        ),
    ]
