# Generated by Django 4.1.7 on 2023-04-09 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_commentproducto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentproducto',
            options={'ordering': ['-created_on'], 'verbose_name': 'Comentario Producto', 'verbose_name_plural': 'Comentarios Producto'},
        ),
    ]
